### ISSUE TITLE
Is training with other public/private dataset allowed?

### ISSUE THREAD

**Issue by hello-world-zsp** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#13]
Hi, 
I'm wondering if the following behavior allowed in this challege:

(1) train/pretrain with lidar sementatic anotations of original NuScenes dataset.
(2) train/pretrain with private SSC anotations of NuScenes dataset.
(3) train/pretrain with other public dataset.
(4) train/pretrain with other private dataset.

If not, how to check  the compliance of the uploaded results. 

Thanks

**Comment by ChonghaoSima** [comment]
First please refer to [general rules](https://docs.google.com/document/d/18wEN6XdSW2VpVgSo0hHEKPN6KPptqvOUv5Znc2_lB3o/view) about using other datasets. 

(1) Allowed
(2) Allowed
(3) Other than ImageNet pre-trained backbone, no other public dataset can be used in the way of either pre-training or joint-training.
(4) Same as above.

In order to check the compliance, there is no direct way to ensure this. Similar to what Waymo have done in previous challenges, we will ask the participants to provide technical reports to the challenge committee and if the participant will be asked to provide a public talk about the method after winning the award.

**Comment by gsg213** [comment]
Hello @ChonghaoSima ,
Regarding the answer to question (1), is allowed to use Lidar's point clouds as input for the proposed architectures?

Thanks!

**Comment by BB88Lee** [comment]
@ChonghaoSima 
Just to confirm, it's not allowed to use lidar points (only in the training phase), such as Bevdepth, right?

**Comment by ChonghaoSima** [comment]
> Hello @ChonghaoSima , Regarding the answer to question (1), is allowed to use Lidar's point clouds as input for the proposed architectures?
> 
> Thanks!

No

**Comment by ChonghaoSima** [comment]
> @ChonghaoSima Just to confirm, it's not allowed to use lidar points (only in the training phase), such as Bevdepth, right?

No limit on how you train the model with any modality, but in inference, only image input is allowed.
